import user from '../views/user/main'
import userRestaurants from '../views/user/restaurant/main'
import userRestaurant from '../views/user/restaurant/single'
import store from '../store/store'

import about from '../views/user/about/main'
import menu from '../views/user/menu/main'
import map from '../views/user/map/main'

import admin from '../views/administration/admin/admin'
import adminRestaurants from '../views/administration/admin/restaurants/restaurants'
import adminManagers from '../views/administration/admin/managers/managers'
import adminClients from '../views/administration/admin/clients/clients'

import manager from '../views/administration/manager/welcome'
import managerRouter from '../views/administration/manager/manager'
import managerFood from '../views/administration/manager/food/food'
import managerTables from '../views/administration/manager/tables/tables'
import managerRestaurant from '../views/administration/manager/restaurant/restaurant'

import login from '../views/auth/login'
import register from '../views/auth/register'


export const routes = 
[{
	name:'login',
	path:'/login',
	component:login
},
{
	name:'mistake',
	path:'/mistake',
	component:login
},
{
	name:'admin',
	path:'/admin',
	component:admin,
	children:[
	{
		name:'admin.restaurants',
		path:'restaurants',
		component:adminRestaurants,
		redirect:{name:'restaurants.dashboard'},
		meta:{
			display:'Restaurants',
			index:0
		},
		children:
		[{
			name:'restaurants.dashboard',
			path:'dashboard',
			component:require('../views/administration/admin/restaurants/dashboard.vue').default,
			meta:{
				display:'Dashboard'
			}
		},
		{
			name:'restaurants.settings',
			path:'settings',
			component:require('../views/administration/admin/restaurants/settings.vue').default,
			meta:{
				display:'Settings'
			}
		}]
	},
	{
		name:'admin.managers',
		path:'managers',
		component:adminManagers,
		redirect:{name:'managers.dashboard'},
		meta:{
			display:'Managers',
			index:1
		},
		children:
		[{
			name:'managers.dashboard',
			path:'dashboard',
			component:require('../views/administration/admin/managers/dashboard.vue').default,
			meta:{
				display:'Dashboard'
			}
		},
		{
			name:'managers.settings',
			path:'settings',
			component:require('../views/administration/admin/managers/settings.vue').default,
			meta:{
				display:'Settings'
			}
		}]
	},
	{
		name:'admin.clients',
		path:'clients',
		component:adminClients,
		redirect:{name:'clients.dashboard'},
		meta:{
			display:'Clients',
			index:2
		},
		children:
		[{
			name:'clients.dashboard',
			path:'dashboard',
			component:require('../views/administration/admin/clients/dashboard.vue').default,
			meta:{
				display:'Dashboard'
			}
		}]

	}],
	beforeEnter:(to,from,next)=>{
		if(!store.state.user.role=='admin'){
			next(false);
		}
		else{
			next({name:'admin.restaurants'});
		}
	}
},
{
	name:'manager',
	path:'/manager',
	component:manager,
	meta:{
		display:"Restaurants"
	},
	beforeEnter:(to,from,next)=>{
		if(store.state.user.role!='manager'){
			next(false);
		}
		else{
			next();
		}	
	}
},
{
	name:'manager.router',
	path:'/manager/edit',
	component:managerRouter,
	redirect:{name:'manager.food'},
	children:
	[{
		name:'manager.food',
		path:'food',
		component:managerFood,
		redirect:{name:'food.dashboard'},
		meta:{
			display:'Menu',
			index:0
		},
		children:
		[{
			name:'food.dashboard',
			path:'dashboard',
			component:require('../views/administration/manager/food/dashboard.vue').default,
			meta:{
				display:'Dashboard'
			}
		},
		{
			name:'food.settings',
			path:'settings',
			component:require('../views/administration/manager/food/settings.vue').default,
			props:true,
			meta:{
				display:'Settings'
			}
		}]
	},
	{
		name:'manager.tables',
		path:'tables',
		component:managerTables,
		redirect:{name:'tables.dashboard'},
		meta:{
			display:'Tables',
			index:1
		},
		children:
		[{
			name:'tables.dashboard',
			path:'dashboard',
			component:require('../views/administration/manager/tables/dashboard.vue').default,
			meta:{
				display:'Dashboard'
			}
		},
		{
			name:'tables.settings',
			path:'settings',
			component:require('../views/administration/manager/tables/settings.vue').default,
			meta:{
				display:'Settings'
			}
		}]
	},
	{
		name:'manager.restaurant',
		path:'restaurant',
		component:managerRestaurant,
		redirect:{name:'restaurant.settings'},
		meta:{
			display:'Restaurant',
			index:2
		},
		children:
		[{
			name:'restaurant.settings',
			path:'settings',
			component:require('../views/administration/manager/restaurant/settings.vue').default,
			props:true,
			meta:{
				display:'Settings'
			}
		}]
	}],
	beforeEnter:(to,from,next)=>{
		if(store.state.user.role!='manager'){
			next(false);
		}
		else{
			next();
		}
	}
},
{
	name:'client',
	path:'/',
	component:user,
	redirect:{name:'about'},
	children:
	[{
		name:'client.restaurant',
		path:'restaurant',
		component:userRestaurant
	},
	{
		name:'about',
		path:'about',
		component:about,
		meta:{
			display:'About',
			icon:'newspaper'
		},
	},
	{
		name:'menu',
		path:'menu',
		component:menu,
		meta:{
			display:'Menu',
			icon:'utensils'
		},

	},
	{
		name:'client.restaurants',
		path:'restaurants',
		component:userRestaurants,
		meta:{
			display:'Restaurants',
			icon:'glass-cheers'
		},
	},
	{
		name:'map',
		path:'map',
		component:map,
		meta:{
			display:'Map',
			icon:'globe'
		},
	}]
},
{
	name:'register',
	path:'/register',
	component:register
}]
